server:
  tomcat:
    use-relative-redirects: true
  forward-headers-strategy: native
spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    defer-datasource-initialization: true
    servlet:
      multipart:
        enabled: true
        location: /var/attachments/temp/
        max-request-size: 20MB
        max-file-size: 20MB