spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      path: /h2-console
      enabled: true
  redis:
    host: localhost
    port: 6379
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace